-- MySQL Script generated by MySQL Workbench
-- Sun Apr 15 16:35:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ping_pong_t_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ping_pong_t_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ping_pong_t_db` DEFAULT CHARACTER SET latin1 ;
USE `ping_pong_t_db` ;

-- -----------------------------------------------------
-- Table `ping_pong_t_db`.`tournament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ping_pong_t_db`.`tournament` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tournamentType` VARCHAR(45) NOT NULL,
  `entryFee` INT(11) NOT NULL,
  `prizePool` INT(11) NOT NULL,
  `winner` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `isFinished` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ping_pong_t_db`.`matchc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ping_pong_t_db`.`matchc` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `tournID` INT(10) NOT NULL,
  `playerOne` INT(10) NOT NULL,
  `playerTwo` INT(10) NOT NULL,
  `playerOneGames` INT(10) NOT NULL,
  `playerTwoGames` INT(10) NOT NULL,
  `matchFinished` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `tournID_idx` (`tournID` ASC),
  INDEX `playerOne_idx` (`playerOne` ASC),
  INDEX `playerTwo_idx` (`playerTwo` ASC),
  CONSTRAINT `tournID`
    FOREIGN KEY (`tournID`)
    REFERENCES `ping_pong_t_db`.`tournament` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ping_pong_t_db`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ping_pong_t_db`.`game` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `MatchID` INT(11) NOT NULL,
  `PlayerOneScore` INT(10) NOT NULL,
  `PlayerTwoScore` INT(10) NOT NULL,
  `gameFinished` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `matchID_idx` (`MatchID` ASC),
  CONSTRAINT `matchID`
    FOREIGN KEY (`MatchID`)
    REFERENCES `ping_pong_t_db`.`matchc` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ping_pong_t_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ping_pong_t_db`.`user` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ping_pong_t_db`.`tournamentplayer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ping_pong_t_db`.`tournamentplayer` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `tournamentID` INT(11) NOT NULL,
  `playerID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `tournamentID_idx` (`tournamentID` ASC),
  INDEX `playerID_idx` (`playerID` ASC),
  CONSTRAINT `playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `ping_pong_t_db`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tournamentID`
    FOREIGN KEY (`tournamentID`)
    REFERENCES `ping_pong_t_db`.`tournament` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ping_pong_t_db`.`userdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ping_pong_t_db`.`userdata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userID` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `balance` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`id`)
    REFERENCES `ping_pong_t_db`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
